# Generated by Django 4.2 on 2024-04-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'ingredients',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measurement', models.CharField(default='', max_length=30)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookbook_app.ingredient')),
            ],
        ),
    ]
