# Generated by Django 4.2 on 2024-04-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table=None,
        ),
    ]
