# Generated by Django 4.2 on 2024-04-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0002_alter_ingredient_options_alter_ingredient_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientset',
            name='parent_recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookbook_app.recipe'),
        ),
    ]
