# Generated by Django 4.2 on 2024-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0003_ingredientset_parent_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientset',
            name='parent_recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='cookbook_app.ingredientset'),
        ),
    ]
