# Generated by Django 4.2 on 2024-04-14 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0004_remove_ingredientset_parent_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientset',
            name='measurement',
        ),
        migrations.AddField(
            model_name='ingredientset',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredientset',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook_app.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientset',
            name='quantity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='cookbook_app.ingredientset'),
        ),
    ]
