# Generated by Django 4.2 on 2024-04-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0005_remove_ingredientset_measurement_ingredientset_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientset',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook_app.ingredient'),
        ),
    ]
